### ISSUE TITLE
Rollup: Plugin Error : Cannot convert undefined or null to object (plugin: env, transform)

### ISSUE THREAD

**Issue by newtonmunene99** [alepop/stencil-env#157]
I am also facing this issue, however, it doesn't seem to be happening on my local development environment, only when I deploy to Netlify.

Version
```
"@stencil/core": "^2.3.0",
```

My config
```
plugins: [
    sass(),
    // env(),
  ],
  rollupPlugins: {
    before: [env()],
    after: [
      // env(),
      nodePolyfills(),
    ],
  },
```
Stencil changed config options and added `rollupPlugins` field. I have tried using it in normal `plugins` field as well as `rollupPlugins.before` and `rollupPlugins.after`

_Originally posted by @newtonmunene99 in https://github.com/alepop/stencil-env/issues/111#issuecomment-745160920_

**Comment by philliphartin** [comment]
I'm also having this issue when using github actions running a simple
- `npm ci`
- `npm run build` 


![CleanShot](https://user-images.githubusercontent.com/1385026/142755796-e663b846-986f-41b0-913f-f4b6c832483b.png)

**Comment by alepop** [comment]
@pjhartin what is a version of node that you use on your local machine and on github actions?

**Comment by philliphartin** [comment]
**Locally** 
Using Node 16.13 LTS
<img width="107" alt="CleanShot 2021-11-26 at 07 31 45@2x" src="https://user-images.githubusercontent.com/1385026/143497545-e43ec0fa-dd1b-4394-b5ec-7f93965518c0.png">

**Github Actions**
Using Node 16 with `actions/setup-node@v2`
 
```yaml
name: Build and Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies      
        run: npm ci
      #- name: Run Tests
      #  run: npm run test
      - name: Build
        run: npm run build
        env:
          GRAPHCMS_CONTENT_API_AUTH_TOKEN: ${{secrets.GRAPHCMS_CONTENT_API_AUTH_TOKEN}}
          GRAPHCMS_CONTENT_API_ENDPOINT: ${{secrets.GRAPHCMS_CONTENT_API_ENDPOINT}}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            loader/
```

**Action Output**
<img width="744" alt="CleanShot 2021-11-26 at 07 41 48@2x" src="https://user-images.githubusercontent.com/1385026/143498186-f0d79766-a310-4991-b974-5686ffdb28d0.png">
